export const listOfImages = [
  '/images/silver_5.jpg',
  '/images/bw_2.jpg',
  '/images/bw_6.png',
  '/images/bw_7.jpg',
  '/images/gold_1.jpg',
  '/images/gold_1a.jpg',
  '/images/gold_1b.jpg', //used
  '/images/oil-blue.jpg',
  '/images/ripples.jpg',
  '/images/silver_1.jpg',
  '/images/silver_4.jpg',
  '/images/silver_6.jpg',
  '/images/silver_9.jpg',
  '/images/silver_12.jpg',
  '/images/silver_14.jpg',
  '/images/img_3.png',
  '/images/img_4.png',
  '/images/img_5.png',
  '/images/img_7.png',
  '/images/platinum_2.jpg',
  '/images/platinum_4.jpg',
  '/images/platinum_7.jpg',
  '/images/coin_2.jpg',  //used
  '/images/coin_7a.jpg',
];